package com.brhn.xpnsr.data

import com.brhn.xpnsr.R
import com.brhn.xpnsr.models.Transaction
import com.brhn.xpnsr.models.TransactionType


fun getCategoryIcon(category: String): Int {
    return when (category) {
        // these samples are generated by AI
        "Groceries" -> R.drawable.baseline_shopping_cart_24
        "Salary", "Freelance", "Dividends", "Investments", "Bonus" -> R.drawable.baseline_attach_money_24
        "Dining", "Cafe" -> R.drawable.baseline_dining_24
        "Fitness", "Gym Membership", "Yoga Classes" -> R.drawable.baseline_fitness_center_24
        "Bills", "Electricity Bill", "Gas Bill" -> R.drawable.baseline_attach_money_24
        "Rent" -> R.drawable.baseline_add_home_24
        "Entertainment", "Movie Night", "Concert Tickets", "Theater Tickets" -> R.drawable.baseline_movie_24
        "Education", "Book Purchase", "Online Course" -> R.drawable.baseline_school_24
        "Transport", "Train Ticket", "Taxi Ride", "Uber Ride" -> R.drawable.baseline_directions_transit_24
        "Insurance", "Car Insurance", "Health Insurance" -> R.drawable.baseline_attach_money_24
        "Gifts", "Birthday Gift" -> R.drawable.baseline_cake_24
        "Healthcare", "Pharmacy", "Pet Vet Visit" -> R.drawable.baseline_medical_services_24
        "Home", "Gardening Supplies", "Garden Tools" -> R.drawable.baseline_local_florist_24
        "Pets", "Pet Food" -> R.drawable.baseline_pets_24
        "Electronics", "Laptop Repair" -> R.drawable.baseline_computer_24
        else -> R.drawable.baseline_do_not_disturb_24
    }
}


fun getSampleTransactions(): List<Transaction> {
    return listOf(
        // these samples are generated by AI
        Transaction(0, "Groceries", "01/01/2024", 50.0, TransactionType.EXPENSE, "Groceries"),
        Transaction(1, "Salary", "05/01/2024", 3000.0, TransactionType.EARNING, "Salary"),
        Transaction(2, "Cafe", "06/01/2024", 15.0, TransactionType.EXPENSE, "Dining"),
        Transaction(3, "Gym Membership", "10/01/2024", 40.0, TransactionType.EXPENSE, "Fitness"),
        Transaction(
            4,
            "Freelance Project",
            "15/01/2024",
            500.0,
            TransactionType.EARNING,
            "Freelance"
        ),
        Transaction(5, "Electricity Bill", "17/01/2024", 60.0, TransactionType.EXPENSE, "Bills"),
        Transaction(6, "Rent", "01/02/2024", 800.0, TransactionType.EXPENSE, "Rent"),
        Transaction(7, "Movie Night", "03/02/2024", 25.0, TransactionType.EXPENSE, "Entertainment"),
        Transaction(8, "Book Purchase", "05/02/2024", 20.0, TransactionType.EXPENSE, "Education"),
        Transaction(9, "Train Ticket", "07/02/2024", 30.0, TransactionType.EXPENSE, "Transport"),
        Transaction(10, "Car Insurance", "10/02/2024", 100.0, TransactionType.EXPENSE, "Insurance"),
        Transaction(11, "Dividends", "12/02/2024", 150.0, TransactionType.EARNING, "Investments"),
        Transaction(12, "Groceries", "15/02/2024", 55.0, TransactionType.EXPENSE, "Groceries"),
        Transaction(13, "Birthday Gift", "20/02/2024", 75.0, TransactionType.EXPENSE, "Gifts"),
        Transaction(
            14,
            "Concert Tickets",
            "23/02/2024",
            90.0,
            TransactionType.EXPENSE,
            "Entertainment"
        ),
        Transaction(15, "Pharmacy", "25/02/2024", 15.0, TransactionType.EXPENSE, "Healthcare"),
        Transaction(16, "Gardening Supplies", "28/02/2024", 35.0, TransactionType.EXPENSE, "Home"),
        Transaction(17, "Pet Food", "02/03/2024", 25.0, TransactionType.EXPENSE, "Pets"),
        Transaction(18, "Taxi Ride", "05/03/2024", 18.0, TransactionType.EXPENSE, "Transport"),
        Transaction(
            19,
            "Laptop Repair",
            "10/03/2024",
            120.0,
            TransactionType.EXPENSE,
            "Electronics"
        ),
        Transaction(20, "Bonus", "15/03/2024", 1000.0, TransactionType.EARNING, "Salary"),
        Transaction(21, "Yoga Classes", "18/03/2024", 70.0, TransactionType.EXPENSE, "Fitness"),
        Transaction(22, "Online Course", "21/03/2024", 200.0, TransactionType.EXPENSE, "Education"),
        Transaction(23, "Dinner Out", "25/03/2024", 60.0, TransactionType.EXPENSE, "Dining"),
        Transaction(
            24,
            "Health Insurance",
            "28/03/2024",
            130.0,
            TransactionType.EXPENSE,
            "Insurance"
        ),
        Transaction(25, "Garden Tools", "01/04/2024", 45.0, TransactionType.EXPENSE, "Home"),
        Transaction(26, "Gas Bill", "04/04/2024", 50.0, TransactionType.EXPENSE, "Bills"),
        Transaction(
            27,
            "Theater Tickets",
            "07/04/2024",
            80.0,
            TransactionType.EXPENSE,
            "Entertainment"
        ),
        Transaction(28, "Pet Vet Visit", "10/04/2024", 100.0, TransactionType.EXPENSE, "Pets"),
        Transaction(29, "Uber Ride", "12/04/2024", 22.0, TransactionType.EXPENSE, "Transport")
    )
}
